#!/bin/bash
#====================================================================
# find_cmds - Find the 3 commands used in these scripts.
# Source this script.
#====================================================================

findcmd() {
  cmd=$1
  shift
  silent=
  case $1 in
    --s*) shift; silent="silent" ;;
  esac
  which -s $cmd > /dev/null
  if [ $? -eq 0 ]
  then
    echo $cmd
    return 0
  fi

  tried=()
  while [ $# -ne 0 ]
  do
    tried=( ${tried[@]} $1 )
    bindir=$(echo $1/bin)
    if [[ -x $bindir/$cmd ]]
    then
      echo $1
      return 0
    fi
    shift
  done
  if [[ -z $silent ]]
  then
    echo "  $0: Could not find '$cmd' on the path or using these environment variables or directories:" 1>&2
    echo "    ${tried[@]}" 1>&2
    echo 1>&2
    help 1>&2
  fi
  return 1
}

find_spark_submit() {
  findcmd spark-submit $@ '$SPARK_HOME' '$SPARKHOME' '$SPARK'
}
find_spark_shell() {
  findcmd spark-shell $@ '$SPARK_HOME' '$SPARKHOME' '$SPARK'
}
find_hadoop() {
  findcmd hadoop $@ '$HADOOP_HOME' '$HADOOPHOME' '$HADOOP'
}
find_activator() {
  findcmd activator $@ '$ACTIVATOR_HOME' '$ACTIVATORHOME' '$ACTIVATOR'
}
find_sbt() {
  findcmd sbt $@ '$SBT_HOME' '$SBTHOME' '$SBT'
}
